import { Inter } from "next/font/google";
import Head from "next/head";
import NavBar from "./components/navbar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>La sonrisa de Bruno</title>
        <meta name="La sonrisa de Bruno" content="La sonrisa de Bruno" />
        <a rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <div className="min-h-screen">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
